# Generated by Django 3.0.1 on 2020-10-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20201026_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
