# Generated by Django 3.0.1 on 2020-11-28 12:55

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_remove_service_type'),
        ('checkout', '0003_auto_20201128_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=40)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=40)),
                ('zipcode', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=80)),
                ('second_address', models.CharField(blank=True, max_length=80, null=True)),
                ('region', models.CharField(blank=True, max_length=80, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('artwork', models.FileField(blank=True, null=True, upload_to='customer_images/%Y/%m/%d')),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('lineitem_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
    ]
