# Generated by Django 3.0.1 on 2020-11-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201129_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vat_amount',
            new_name='vat',
        ),
    ]
