# Generated by Django 3.0.1 on 2020-11-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='artwork',
            field=models.FileField(blank=True, null=True, upload_to='customer_images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
