# Generated by Django 3.0.1 on 2020-11-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20201130_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='artwork',
        ),
    ]
