# Generated by Django 3.0.1 on 2020-11-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_remove_order_artwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
